export interface BovScheduleTask {
  task_no: number;
  wbs_code: string;
  title: string;
  duration: string;
  start: string;
  end: string;
  assignee: string;
  trade: string;
  progress: number;
  status: "Completed" | "In Progress" | "Not Started";
  is_summary: number; // 0 or 1
  is_milestone: number; // 0 or 1
}

export const BOV_MS_PROJECT_SCHEDULE: BovScheduleTask[] = [
  // Page 1
  {
    task_no: 1,
    wbs_code: "1.0",
    title: "1.0 Design",
    duration: "5 days",
    start: "2026-09-14",
    end: "2026-09-18",
    assignee: "PM,Electrician",
    trade: "Engineering",
    progress: 100,
    status: "Completed",
    is_summary: 1,
    is_milestone: 0
  },
  {
    task_no: 2,
    wbs_code: "1.1",
    title: "Review RFQ, site information and existing services",
    duration: "1 day",
    start: "2026-09-14",
    end: "2026-09-14",
    assignee: "PM,Electrician",
    trade: "Engineering",
    progress: 100,
    status: "Completed",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 3,
    wbs_code: "1.2",
    title: "Site survey and verify reusable containment",
    duration: "1 day",
    start: "2026-09-15",
    end: "2026-09-15",
    assignee: "PM,Electrician",
    trade: "Electrical",
    progress: 100,
    status: "Completed",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 4,
    wbs_code: "1.3",
    title: "Prepare coordinated electrical/data/AV/UPS drawings and DB schedules",
    duration: "2 days",
    start: "2026-09-16",
    end: "2026-09-17",
    assignee: "PM,CAD Engineer",
    trade: "Engineering",
    progress: 100,
    status: "Completed",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 5,
    wbs_code: "1.4",
    title: "Submit coordinated working drawings for approval",
    duration: "1 day",
    start: "2026-09-18",
    end: "2026-09-18",
    assignee: "PM",
    trade: "Management",
    progress: 100,
    status: "Completed",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 6,
    wbs_code: "2.0",
    title: "2.0 Approval",
    duration: "7 days",
    start: "2026-09-18",
    end: "2026-09-25",
    assignee: "Client Engineer,PM",
    trade: "Client/Consultant",
    progress: 100,
    status: "Completed",
    is_summary: 1,
    is_milestone: 0
  },
  {
    task_no: 7,
    wbs_code: "2.1",
    title: "Client/Engineer drawing review and approval",
    duration: "7 days",
    start: "2026-09-18",
    end: "2026-09-25",
    assignee: "Client Engineer,PM",
    trade: "Client/Consultant",
    progress: 100,
    status: "Completed",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 8,
    wbs_code: "2.2",
    title: "Approved drawings issued",
    duration: "1 day",
    start: "2026-09-25",
    end: "2026-09-25",
    assignee: "Client Engineer",
    trade: "Client/Consultant",
    progress: 100,
    status: "Completed",
    is_summary: 0,
    is_milestone: 1
  },
  {
    task_no: 9,
    wbs_code: "3.0",
    title: "3.0 Procurement",
    duration: "3 days",
    start: "2026-09-28",
    end: "2026-09-30",
    assignee: "PM,Procurement",
    trade: "Procurement",
    progress: 100,
    status: "Completed",
    is_summary: 1,
    is_milestone: 0
  },
  {
    task_no: 10,
    wbs_code: "3.1",
    title: "Procurement of all project materials, delivery coordination",
    duration: "3 days",
    start: "2026-09-28",
    end: "2026-09-30",
    assignee: "PM,Procurement",
    trade: "Procurement",
    progress: 100,
    status: "Completed",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 11,
    wbs_code: "4.0",
    title: "4.0 Construction",
    duration: "1 day",
    start: "2026-10-01",
    end: "2026-10-01",
    assignee: "PM",
    trade: "Management",
    progress: 100,
    status: "Completed",
    is_summary: 1,
    is_milestone: 0
  },
  {
    task_no: 12,
    wbs_code: "4.1",
    title: "Construction commences",
    duration: "1 day",
    start: "2026-10-01",
    end: "2026-10-01",
    assignee: "PM",
    trade: "Management",
    progress: 100,
    status: "Completed",
    is_summary: 0,
    is_milestone: 1
  },
  {
    task_no: 13,
    wbs_code: "5.0",
    title: "5.0 Week 1 - Dismantling",
    duration: "4 days",
    start: "2026-10-01",
    end: "2026-10-05",
    assignee: "Electrical Team",
    trade: "Electrical",
    progress: 100,
    status: "Completed",
    is_summary: 1,
    is_milestone: 0
  },
  {
    task_no: 14,
    wbs_code: "5.1",
    title: "Level 1 safe isolation and dismantling",
    duration: "2 days",
    start: "2026-10-01",
    end: "2026-10-02",
    assignee: "Electrical Team",
    trade: "Electrical",
    progress: 100,
    status: "Completed",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 15,
    wbs_code: "5.2",
    title: "Level 2 safe isolation and dismantling",
    duration: "2 days",
    start: "2026-10-03",
    end: "2026-10-05",
    assignee: "Electrical Team",
    trade: "Electrical",
    progress: 100,
    status: "Completed",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 16,
    wbs_code: "6.0",
    title: "6.0 Week 1 - Survey",
    duration: "2 days",
    start: "2026-10-06",
    end: "2026-10-07",
    assignee: "Electrical Team",
    trade: "Electrical",
    progress: 100,
    status: "Completed",
    is_summary: 1,
    is_milestone: 0
  },
  {
    task_no: 17,
    wbs_code: "6.1",
    title: "Inspect, clear and approve existing containment routes",
    duration: "1 day",
    start: "2026-10-06",
    end: "2026-10-06",
    assignee: "Electrical Team",
    trade: "Electrical",
    progress: 100,
    status: "Completed",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 18,
    wbs_code: "6.2",
    title: "Set out new boxes, conduit extensions, supports and penetrations",
    duration: "1 day",
    start: "2026-10-07",
    end: "2026-10-07",
    assignee: "Electrical Team",
    trade: "Electrical",
    progress: 100,
    status: "Completed",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 19,
    wbs_code: "7.0",
    title: "7.0 1st Fix - Containment, Conduits, Boxes and Supports",
    duration: "5 days",
    start: "2026-10-08",
    end: "2026-10-13",
    assignee: "Electrical Team",
    trade: "Electrical",
    progress: 85,
    status: "In Progress",
    is_summary: 1,
    is_milestone: 0
  },
  {
    task_no: 20,
    wbs_code: "7.1",
    title: "Level 1 first fix - missing conduit, boxes and supports",
    duration: "3 days",
    start: "2026-10-08",
    end: "2026-10-10",
    assignee: "Electrical Team",
    trade: "Electrical",
    progress: 90,
    status: "In Progress",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 21,
    wbs_code: "7.2",
    title: "Level 2 first fix - missing conduit, boxes and supports",
    duration: "3 days",
    start: "2026-10-08",
    end: "2026-10-10",
    assignee: "Electrical Team",
    trade: "Electrical",
    progress: 80,
    status: "In Progress",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 22,
    wbs_code: "7.3",
    title: "DB/UPS bases, power-pole supports, GOP/media boxes and floor boxes",
    duration: "2 days",
    start: "2026-10-12",
    end: "2026-10-13",
    assignee: "Electrical Team",
    trade: "Electrical",
    progress: 75,
    status: "In Progress",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 23,
    wbs_code: "8.0",
    title: "8.0 RFQ First-Fix Activities",
    duration: "4 days",
    start: "2026-10-08",
    end: "2026-10-12",
    assignee: "Electrician,PM",
    trade: "Electrical",
    progress: 70,
    status: "In Progress",
    is_summary: 1,
    is_milestone: 0
  },
  {
    task_no: 24,
    wbs_code: "8.1",
    title: "Lighting points first fix complete - 130 No.",
    duration: "4 days",
    start: "2026-10-08",
    end: "2026-10-12",
    assignee: "Electrician,PM",
    trade: "Electrical",
    progress: 80,
    status: "In Progress",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 25,
    wbs_code: "8.2",
    title: "Dimmable lighting points first fix complete - 6 No.",
    duration: "1 day",
    start: "2026-10-08",
    end: "2026-10-08",
    assignee: "Electrician,PM",
    trade: "Electrical",
    progress: 100,
    status: "Completed",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 26,
    wbs_code: "8.3",
    title: "Emergency lighting points first fix complete - 26 No.",
    duration: "2 days",
    start: "2026-10-08",
    end: "2026-10-09",
    assignee: "Electrician,PM",
    trade: "Electrical",
    progress: 100,
    status: "Completed",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 27,
    wbs_code: "8.4",
    title: "PIR sensor points first fix complete - 27 No.",
    duration: "3 days",
    start: "2026-10-08",
    end: "2026-10-10",
    assignee: "Electrician,PM",
    trade: "Electrical",
    progress: 90,
    status: "In Progress",
    is_summary: 0,
    is_milestone: 0
  },

  // Page 2
  {
    task_no: 28,
    wbs_code: "8.5",
    title: "Switch/dimmer boxes and routes complete - 6 x 1G1W; 1 x 2G1W; 2 x 2G2W; 1 dimmer",
    duration: "1 day",
    start: "2026-10-08",
    end: "2026-10-08",
    assignee: "Electrician,PM",
    trade: "Electrical",
    progress: 100,
    status: "Completed",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 29,
    wbs_code: "8.6",
    title: "Socket routes complete - 67 twin; 6 floor-box; 2 media-plate; 2 IP65",
    duration: "3 days",
    start: "2026-10-08",
    end: "2026-10-10",
    assignee: "Electrician,PM",
    trade: "Electrical",
    progress: 85,
    status: "In Progress",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 30,
    wbs_code: "8.7",
    title: "FCU routes complete - 43 switched and 5 unswitched",
    duration: "3 days",
    start: "2026-10-08",
    end: "2026-10-10",
    assignee: "Electrician,PM",
    trade: "Electrical",
    progress: 80,
    status: "In Progress",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 31,
    wbs_code: "8.8",
    title: "20A 2P rotary-isolator routes complete - 27 No.",
    duration: "3 days",
    start: "2026-10-08",
    end: "2026-10-10",
    assignee: "Electrician,PM",
    trade: "Electrical",
    progress: 75,
    status: "In Progress",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 32,
    wbs_code: "8.9",
    title: "AC controller conduits complete - 3 No.",
    duration: "1 day",
    start: "2026-10-08",
    end: "2026-10-08",
    assignee: "Electrician,PM",
    trade: "Electrical",
    progress: 100,
    status: "Completed",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 33,
    wbs_code: "8.10",
    title: "Manual call-point conduit complete - 1 No.",
    duration: "1 day",
    start: "2026-10-08",
    end: "2026-10-08",
    assignee: "Electrician,PM",
    trade: "Electrical",
    progress: 100,
    status: "Completed",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 34,
    wbs_code: "8.11",
    title: "Media box conduit for 2 data points complete - 1 No.",
    duration: "1 day",
    start: "2026-10-08",
    end: "2026-10-08",
    assignee: "Electrician,PM",
    trade: "ELV/Data",
    progress: 100,
    status: "Completed",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 35,
    wbs_code: "8.12",
    title: "Single data-point conduits complete - 22 No.",
    duration: "2 days",
    start: "2026-10-08",
    end: "2026-10-09",
    assignee: "Electrician,PM",
    trade: "ELV/Data",
    progress: 100,
    status: "Completed",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 36,
    wbs_code: "8.13",
    title: "Two data-point conduits complete - 3 No.",
    duration: "1 day",
    start: "2026-10-08",
    end: "2026-10-08",
    assignee: "Electrician,PM",
    trade: "ELV/Data",
    progress: 100,
    status: "Completed",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 37,
    wbs_code: "8.14",
    title: "Four data-point conduit group complete - 1 No.",
    duration: "1 day",
    start: "2026-10-08",
    end: "2026-10-08",
    assignee: "Electrician,PM",
    trade: "ELV/Data",
    progress: 100,
    status: "Completed",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 38,
    wbs_code: "8.15",
    title: "Wi-Fi 25mm conduits complete - 9 No.",
    duration: "2 days",
    start: "2026-10-08",
    end: "2026-10-09",
    assignee: "Electrician,PM",
    trade: "ELV/Data",
    progress: 100,
    status: "Completed",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 39,
    wbs_code: "8.16",
    title: "Intruder keypad conduit complete - 1 No.",
    duration: "1 day",
    start: "2026-10-08",
    end: "2026-10-08",
    assignee: "Electrician,PM",
    trade: "ELV/Data",
    progress: 100,
    status: "Completed",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 40,
    wbs_code: "8.17",
    title: "Intruder sensor conduits complete - 5 No.",
    duration: "1 day",
    start: "2026-10-08",
    end: "2026-10-08",
    assignee: "Electrician,PM",
    trade: "ELV/Data",
    progress: 100,
    status: "Completed",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 41,
    wbs_code: "8.18",
    title: "Proximity-reader conduits complete - 6 No.",
    duration: "1 day",
    start: "2026-10-08",
    end: "2026-10-08",
    assignee: "Electrician,PM",
    trade: "ELV/Data",
    progress: 100,
    status: "Completed",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 42,
    wbs_code: "8.19",
    title: "Door-access panel conduits complete - 5 No.",
    duration: "1 day",
    start: "2026-10-08",
    end: "2026-10-08",
    assignee: "Electrician,PM",
    trade: "ELV/Data",
    progress: 100,
    status: "Completed",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 43,
    wbs_code: "8.20",
    title: "Recessed speaker conduits complete - 4 No.",
    duration: "1 day",
    start: "2026-10-08",
    end: "2026-10-08",
    assignee: "Electrician,PM",
    trade: "ELV/Data",
    progress: 100,
    status: "Completed",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 44,
    wbs_code: "8.21",
    title: "Bluetooth receiver panel conduit complete - 1 No.",
    duration: "1 day",
    start: "2026-10-08",
    end: "2026-10-08",
    assignee: "Electrician,PM",
    trade: "ELV/Data",
    progress: 100,
    status: "Completed",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 45,
    wbs_code: "8.22",
    title: "Penetration register approved and openings exceeding 100x100mm authorised",
    duration: "1 day",
    start: "2026-10-08",
    end: "2026-10-08",
    assignee: "Electrician,PM",
    trade: "QA/QC",
    progress: 100,
    status: "Completed",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 46,
    wbs_code: "9.0",
    title: "9.0 1st Fix - Inspection and Approval",
    duration: "1 day",
    start: "2026-10-14",
    end: "2026-10-14",
    assignee: "Electrician,Client Engineer",
    trade: "QA/QC",
    progress: 50,
    status: "In Progress",
    is_summary: 1,
    is_milestone: 0
  },
  {
    task_no: 47,
    wbs_code: "9.1",
    title: "First-fix inspection, photographs and concealed-work approval",
    duration: "1 day",
    start: "2026-10-14",
    end: "2026-10-14",
    assignee: "Electrician,Client Engineer",
    trade: "QA/QC",
    progress: 50,
    status: "In Progress",
    is_summary: 0,
    is_milestone: 1
  },
  {
    task_no: 48,
    wbs_code: "10.0",
    title: "10.0 Week 3 - Cable Pulling",
    duration: "6 days",
    start: "2026-10-15",
    end: "2026-10-21",
    assignee: "Electrical Team",
    trade: "Electrical",
    progress: 20,
    status: "In Progress",
    is_summary: 1,
    is_milestone: 0
  },
  {
    task_no: 49,
    wbs_code: "10.1",
    title: "Level 1 power, lighting, emergency and control cable pulling",
    duration: "3 days",
    start: "2026-10-15",
    end: "2026-10-17",
    assignee: "Electrical Team",
    trade: "Electrical",
    progress: 30,
    status: "In Progress",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 50,
    wbs_code: "10.2",
    title: "Level 2 power, lighting, emergency and control cable pulling",
    duration: "3 days",
    start: "2026-10-15",
    end: "2026-10-17",
    assignee: "Electrical Team",
    trade: "Electrical",
    progress: 20,
    status: "In Progress",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 51,
    wbs_code: "10.3",
    title: "CAT6, Wi-Fi, HDMI and speaker cable pulling - both floors",
    duration: "5 days",
    start: "2026-10-15",
    end: "2026-10-20",
    assignee: "Electrical Team",
    trade: "ELV/Data",
    progress: 15,
    status: "In Progress",
    is_summary: 0,
    is_milestone: 0
  },

  // Page 3
  {
    task_no: 52,
    wbs_code: "10.4",
    title: "Complete difficult pulls, feeders and desk power feeds",
    duration: "2 days",
    start: "2026-10-20",
    end: "2026-10-21",
    assignee: "Electrical Team",
    trade: "Electrical",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 53,
    wbs_code: "11.0",
    title: "11.0 RFQ Cable Installation Activities",
    duration: "5 days",
    start: "2026-10-15",
    end: "2026-10-20",
    assignee: "Electrical Team",
    trade: "Electrical",
    progress: 20,
    status: "In Progress",
    is_summary: 1,
    is_milestone: 0
  },
  {
    task_no: 54,
    wbs_code: "11.1",
    title: "New feeders C04-C08/C10/C11 installed and identified",
    duration: "2 days",
    start: "2026-10-15",
    end: "2026-10-16",
    assignee: "Electrical Team",
    trade: "Electrical",
    progress: 40,
    status: "In Progress",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 55,
    wbs_code: "11.2",
    title: "New feeder cable ends terminated with nylon glands - 14",
    duration: "2 days",
    start: "2026-10-15",
    end: "2026-10-16",
    assignee: "Electrical Team",
    trade: "Electrical",
    progress: 30,
    status: "In Progress",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 56,
    wbs_code: "11.3",
    title: "Existing C01/C02/C03/C09 reterminated with BW glands - 8 terminations",
    duration: "2 days",
    start: "2026-10-15",
    end: "2026-10-16",
    assignee: "Electrical Team",
    trade: "Electrical",
    progress: 20,
    status: "In Progress",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 57,
    wbs_code: "11.4",
    title: "Lighting/emergency/PIR/control LSZH cabling installed",
    duration: "3 days",
    start: "2026-10-15",
    end: "2026-10-17",
    assignee: "Electrical Team",
    trade: "Electrical",
    progress: 25,
    status: "In Progress",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 58,
    wbs_code: "11.5",
    title: "Power/socket/FCU/isolator/desk-feed LSZH cabling installed",
    duration: "3 days",
    start: "2026-10-15",
    end: "2026-10-17",
    assignee: "Electrical Team",
    trade: "Electrical",
    progress: 20,
    status: "In Progress",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 59,
    wbs_code: "11.6",
    title: "CAT6 F/UTP Wi-Fi cable installed - 400m",
    duration: "3 days",
    start: "2026-10-15",
    end: "2026-10-17",
    assignee: "Electrical Team",
    trade: "ELV/Data",
    progress: 30,
    status: "In Progress",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 60,
    wbs_code: "11.7",
    title: "CAT6 U/UTP general cable installed - 3,070m",
    duration: "5 days",
    start: "2026-10-15",
    end: "2026-10-20",
    assignee: "Electrical Team",
    trade: "ELV/Data",
    progress: 15,
    status: "In Progress",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 61,
    wbs_code: "11.8",
    title: "Desk patch cabling installed through poles/baskets - 460m",
    duration: "3 days",
    start: "2026-10-15",
    end: "2026-10-17",
    assignee: "Electrical Team",
    trade: "ELV/Data",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 62,
    wbs_code: "11.9",
    title: "Speaker cable installed - 50m",
    duration: "2 days",
    start: "2026-10-15",
    end: "2026-10-16",
    assignee: "Electrical Team",
    trade: "ELV/Data",
    progress: 20,
    status: "In Progress",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 63,
    wbs_code: "11.10",
    title: "AOC HDMI installed at all ten scheduled lengths",
    duration: "2 days",
    start: "2026-10-15",
    end: "2026-10-16",
    assignee: "Electrical Team",
    trade: "ELV/Data",
    progress: 10,
    status: "In Progress",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 64,
    wbs_code: "12.0",
    title: "12.0 Week 3 - Gate",
    duration: "1 day",
    start: "2026-10-21",
    end: "2026-10-21",
    assignee: "Electrician,PM",
    trade: "Management",
    progress: 0,
    status: "Not Started",
    is_summary: 1,
    is_milestone: 0
  },
  {
    task_no: 65,
    wbs_code: "12.1",
    title: "Cable-pulling reconciliation and 90% completion gate",
    duration: "1 day",
    start: "2026-10-21",
    end: "2026-10-21",
    assignee: "Electrician,PM",
    trade: "QA/QC",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 1
  },
  {
    task_no: 66,
    wbs_code: "13.0",
    title: "13.0 2nd Fix - Cables, Fittings and Equipment",
    duration: "3 days",
    start: "2026-10-22",
    end: "2026-10-24",
    assignee: "Electrical Team",
    trade: "Electrical",
    progress: 0,
    status: "Not Started",
    is_summary: 1,
    is_milestone: 0
  },
  {
    task_no: 67,
    wbs_code: "13.1",
    title: "Level 1 second fix - fittings, accessories and isolators",
    duration: "3 days",
    start: "2026-10-22",
    end: "2026-10-24",
    assignee: "Electrical Team",
    trade: "Electrical",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 68,
    wbs_code: "13.2",
    title: "Level 2 second fix - fittings, accessories and isolators",
    duration: "3 days",
    start: "2026-10-22",
    end: "2026-10-24",
    assignee: "Electrical Team",
    trade: "Electrical",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 69,
    wbs_code: "14.0",
    title: "14.0 2nd Fix - Data, AV and Desk Services",
    duration: "5 days",
    start: "2026-10-22",
    end: "2026-10-27",
    assignee: "Electrical Team",
    trade: "ELV/Data",
    progress: 0,
    status: "Not Started",
    is_summary: 1,
    is_milestone: 0
  },
  {
    task_no: 70,
    wbs_code: "14.1",
    title: "Data/GOP outlets, power poles, GST and desk units",
    duration: "3 days",
    start: "2026-10-22",
    end: "2026-10-24",
    assignee: "Electrical Team",
    trade: "Electrical",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 71,
    wbs_code: "14.2",
    title: "TV supports, HDMI distribution and audio equipment",
    duration: "2 days",
    start: "2026-10-26",
    end: "2026-10-27",
    assignee: "Electrical Team",
    trade: "ELV/Data",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 72,
    wbs_code: "15.0",
    title: "15.0 RFQ Second-Fix Activities",
    duration: "5 days",
    start: "2026-10-22",
    end: "2026-10-27",
    assignee: "PM,Electrical Team",
    trade: "Electrical",
    progress: 0,
    status: "Not Started",
    is_summary: 1,
    is_milestone: 0
  },
  {
    task_no: 73,
    wbs_code: "15.1",
    title: "UP0 installed; DB1/DB2/UP1/UP2 device modifications complete",
    duration: "1 day",
    start: "2026-10-22",
    end: "2026-10-22",
    assignee: "PM,Electrical Team",
    trade: "Electrical",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 74,
    wbs_code: "15.2",
    title: "63A isolators and 16A industrial sockets installed - 2 each",
    duration: "1 day",
    start: "2026-10-22",
    end: "2026-10-22",
    assignee: "PM,Electrical Team",
    trade: "Electrical",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 75,
    wbs_code: "15.3",
    title: "Lighting fittings Type A 77 / B 31 / C 6 / D 5 installed",
    duration: "5 days",
    start: "2026-10-22",
    end: "2026-10-27",
    assignee: "PM,Electrical Team",
    trade: "Electrical",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },

  // Page 4
  {
    task_no: 76,
    wbs_code: "15.4",
    title: "Emergency fittings Type E1 20 / E2 6 installed",
    duration: "2 days",
    start: "2026-10-22",
    end: "2026-10-23",
    assignee: "PM,Electrical Team",
    trade: "Electrical",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 77,
    wbs_code: "15.5",
    title: "Fittings Type F 1 / G 6 / H 2 / I 8 installed",
    duration: "2 days",
    start: "2026-10-22",
    end: "2026-10-23",
    assignee: "PM,Electrical Team",
    trade: "Electrical",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 78,
    wbs_code: "15.6",
    title: "Switches, dimmer, PIRs, sockets, FCUs and 20A isolators fixed",
    duration: "3 days",
    start: "2026-10-22",
    end: "2026-10-24",
    assignee: "PM,Electrical Team",
    trade: "Electrical",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 79,
    wbs_code: "15.7",
    title: "Existing floor-to-ceiling power poles reinstalled - 10 No.",
    duration: "3 days",
    start: "2026-10-22",
    end: "2026-10-24",
    assignee: "PM,Electrical Team",
    trade: "Electrical",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 80,
    wbs_code: "15.8",
    title: "GST 1in3out couplers 22 and 1in2out couplers 5 installed",
    duration: "1 day",
    start: "2026-10-22",
    end: "2026-10-22",
    assignee: "PM,Electrical Team",
    trade: "Electrical",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 81,
    wbs_code: "15.9",
    title: "GST M/F leads installed - 1m x27 and 2m x22",
    duration: "1 day",
    start: "2026-10-22",
    end: "2026-10-22",
    assignee: "PM,Electrical Team",
    trade: "Electrical",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 82,
    wbs_code: "15.10",
    title: "GST female-to-13A plug leads installed - 1m x5 and 2m x1",
    duration: "1 day",
    start: "2026-10-22",
    end: "2026-10-22",
    assignee: "PM,Electrical Team",
    trade: "Electrical",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 83,
    wbs_code: "15.11",
    title: "Desk combination units installed - 82 No.; desk spine - 1 No.",
    duration: "4 days",
    start: "2026-10-22",
    end: "2026-10-26",
    assignee: "PM,Electrical Team",
    trade: "Electrical",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 84,
    wbs_code: "15.12",
    title: "GOP boxes installed in all five scheduled sizes - 10 total",
    duration: "2 days",
    start: "2026-10-22",
    end: "2026-10-23",
    assignee: "PM,Electrical Team",
    trade: "ELV/Data",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 85,
    wbs_code: "15.13",
    title: "Data outlets installed - 1-port x1; 2-port x3; FTP Wi-Fi x9; 4-port x1",
    duration: "2 days",
    start: "2026-10-22",
    end: "2026-10-23",
    assignee: "PM,Electrical Team",
    trade: "ELV/Data",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 86,
    wbs_code: "15.14",
    title: "CAT6 Euromodules installed - 14 No.; 4K HDMI Euromodule - 1 No.",
    duration: "1 day",
    start: "2026-10-22",
    end: "2026-10-22",
    assignee: "PM,Electrical Team",
    trade: "ELV/Data",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 87,
    wbs_code: "15.15",
    title: "Wi-Fi access points installed - 9 No.",
    duration: "2 days",
    start: "2026-10-22",
    end: "2026-10-23",
    assignee: "PM,Electrical Team",
    trade: "ELV/Data",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 88,
    wbs_code: "15.16",
    title: "HDMI distribution system and AOC cables installed",
    duration: "2 days",
    start: "2026-10-22",
    end: "2026-10-23",
    assignee: "PM,Electrical Team",
    trade: "ELV/Data",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 89,
    wbs_code: "15.17",
    title: "Ceiling-mounted TVs installed - 10; wall-mounted TVs - 4",
    duration: "3 days",
    start: "2026-10-22",
    end: "2026-10-24",
    assignee: "PM,Electrical Team",
    trade: "ELV/Data",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 90,
    wbs_code: "15.18",
    title: "100V amplifier, 6 ceiling speakers and Bluetooth panel installed",
    duration: "2 days",
    start: "2026-10-22",
    end: "2026-10-23",
    assignee: "PM,Electrical Team",
    trade: "ELV/Data",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 91,
    wbs_code: "15.19",
    title: "20kVA UPS positioned in first-floor server room and power/network interfaces installed",
    duration: "3 days",
    start: "2026-10-22",
    end: "2026-10-24",
    assignee: "PM,Electrical Team",
    trade: "Electrical",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 92,
    wbs_code: "16.0",
    title: "16.0 2nd Fix - Panels and UPS",
    duration: "2 days",
    start: "2026-10-26",
    end: "2026-10-27",
    assignee: "Electrical Team",
    trade: "Electrical",
    progress: 0,
    status: "Not Started",
    is_summary: 1,
    is_milestone: 0
  },
  {
    task_no: 93,
    wbs_code: "16.1",
    title: "Install UP0 and modify existing DB1/DB2/UP1/UP2",
    duration: "2 days",
    start: "2026-10-26",
    end: "2026-10-27",
    assignee: "Electrical Team",
    trade: "Electrical",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 94,
    wbs_code: "17.0",
    title: "17.0 Week 4 - Gate",
    duration: "1 day",
    start: "2026-10-28",
    end: "2026-10-28",
    assignee: "Electrical Team",
    trade: "Management",
    progress: 0,
    status: "Not Started",
    is_summary: 1,
    is_milestone: 0
  },
  {
    task_no: 95,
    wbs_code: "17.1",
    title: "Second-fix QA and pre-termination testing",
    duration: "1 day",
    start: "2026-10-28",
    end: "2026-10-28",
    assignee: "Electrical Team",
    trade: "QA/QC",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 1
  },
  {
    task_no: 96,
    wbs_code: "18.0",
    title: "18.0 3rd Fix - Final Accessories and Terminations",
    duration: "3 days",
    start: "2026-10-29",
    end: "2026-10-31",
    assignee: "Electrical Team",
    trade: "Electrical",
    progress: 0,
    status: "Not Started",
    is_summary: 1,
    is_milestone: 0
  },
  {
    task_no: 97,
    wbs_code: "18.1",
    title: "Level 1 third fix and DB/field terminations",
    duration: "3 days",
    start: "2026-10-29",
    end: "2026-10-31",
    assignee: "Electrical Team",
    trade: "Electrical",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 98,
    wbs_code: "18.2",
    title: "Level 2 third fix and DB/field terminations",
    duration: "3 days",
    start: "2026-10-29",
    end: "2026-10-31",
    assignee: "Electrical Team",
    trade: "Electrical",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 99,
    wbs_code: "19.0",
    title: "19.0 3rd Fix - Data and AV Termination",
    duration: "4 days",
    start: "2026-10-29",
    end: "2026-11-02",
    assignee: "Electrical Team",
    trade: "ELV/Data",
    progress: 0,
    status: "Not Started",
    is_summary: 1,
    is_milestone: 0
  },

  // Page 5
  {
    task_no: 100,
    wbs_code: "19.1",
    title: "CAT6 terminations and progressive certification",
    duration: "4 days",
    start: "2026-10-29",
    end: "2026-11-02",
    assignee: "Electrical Team",
    trade: "ELV/Data",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 101,
    wbs_code: "20.0",
    title: "20.0 RFQ Third-Fix Activities",
    duration: "4 days",
    start: "2026-10-29",
    end: "2026-11-02",
    assignee: "Electrician,PM",
    trade: "Electrical",
    progress: 0,
    status: "Not Started",
    is_summary: 1,
    is_milestone: 0
  },
  {
    task_no: 102,
    wbs_code: "20.1",
    title: "All panel/isolator feeder terminations torqued, shrouded",
    duration: "3 days",
    start: "2026-10-29",
    end: "2026-10-31",
    assignee: "Electrician,PM",
    trade: "Electrical",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 103,
    wbs_code: "20.2",
    title: "All lighting, emergency, PIR, switch, socket, FCU and desk-power terminations complete",
    duration: "3 days",
    start: "2026-10-29",
    end: "2026-10-31",
    assignee: "Electrician,PM",
    trade: "Electrical",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 104,
    wbs_code: "20.3",
    title: "CAT6 F/UTP Wi-Fi terminations complete - 36 No.",
    duration: "2 days",
    start: "2026-10-29",
    end: "2026-10-30",
    assignee: "Electrician,PM",
    trade: "ELV/Data",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 105,
    wbs_code: "20.4",
    title: "CAT6 U/UTP general terminations complete - 288 No.",
    duration: "4 days",
    start: "2026-10-29",
    end: "2026-11-02",
    assignee: "Electrician,PM",
    trade: "ELV/Data",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 106,
    wbs_code: "20.5",
    title: "CAT6 desk patch terminations complete - 152 No.",
    duration: "3 days",
    start: "2026-10-29",
    end: "2026-10-31",
    assignee: "Electrician,PM",
    trade: "ELV/Data",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 107,
    wbs_code: "20.6",
    title: "All electrical panels, cables and isolators labelled; DB schedules installed",
    duration: "1 day",
    start: "2026-10-29",
    end: "2026-10-29",
    assignee: "Electrician,PM",
    trade: "Electrical",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 108,
    wbs_code: "20.7",
    title: "UPS-connected accessories and circuits labelled UPS",
    duration: "1 day",
    start: "2026-10-29",
    end: "2026-10-29",
    assignee: "Electrician,PM",
    trade: "Electrical",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 109,
    wbs_code: "20.8",
    title: "All data outlets labelled with unique identifiers",
    duration: "1 day",
    start: "2026-10-29",
    end: "2026-10-29",
    assignee: "Electrician,PM",
    trade: "ELV/Data",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 110,
    wbs_code: "20.9",
    title: "All power/containment penetrations permanently sealed",
    duration: "1 day",
    start: "2026-10-29",
    end: "2026-10-29",
    assignee: "Electrician,PM",
    trade: "Electrical",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 111,
    wbs_code: "21.0",
    title: "21.0 3rd Fix - Labelling and Final Records",
    duration: "2 days",
    start: "2026-11-03",
    end: "2026-11-04",
    assignee: "Electrical Team",
    trade: "Electrical",
    progress: 0,
    status: "Not Started",
    is_summary: 1,
    is_milestone: 0
  },
  {
    task_no: 112,
    wbs_code: "21.1",
    title: "AV/UPS final connections, labels, schedules and torque records",
    duration: "2 days",
    start: "2026-11-03",
    end: "2026-11-04",
    assignee: "Electrical Team",
    trade: "Electrical",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 113,
    wbs_code: "22.0",
    title: "22.0 Week 5 - Gate",
    duration: "1 day",
    start: "2026-11-04",
    end: "2026-11-04",
    assignee: "Electrician,PM",
    trade: "Management",
    progress: 0,
    status: "Not Started",
    is_summary: 1,
    is_milestone: 0
  },
  {
    task_no: 114,
    wbs_code: "22.1",
    title: "Third-fix sign-off and 48-hour testing notice",
    duration: "1 day",
    start: "2026-11-04",
    end: "2026-11-04",
    assignee: "Electrician,PM",
    trade: "QA/QC",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 1
  },
  {
    task_no: 115,
    wbs_code: "23.0",
    title: "23.0 Week 6 - Testing",
    duration: "3 days",
    start: "2026-11-05",
    end: "2026-11-07",
    assignee: "Electrical Team,Engineer",
    trade: "QA/QC",
    progress: 0,
    status: "Not Started",
    is_summary: 1,
    is_milestone: 0
  },
  {
    task_no: 116,
    wbs_code: "23.1",
    title: "BS 7671 pre-energisation tests A-G as relevant",
    duration: "1 day",
    start: "2026-11-05",
    end: "2026-11-05",
    assignee: "Electrical Team,Engineer",
    trade: "QA/QC",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 117,
    wbs_code: "23.2",
    title: "Energisation and BS 7671 tests H-M as relevant",
    duration: "1 day",
    start: "2026-11-06",
    end: "2026-11-06",
    assignee: "Electrical Team,Engineer",
    trade: "QA/QC",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 118,
    wbs_code: "23.3",
    title: "Complete 100% CAT6 certification and retesting",
    duration: "1 day",
    start: "2026-11-07",
    end: "2026-11-07",
    assignee: "Electrical Team",
    trade: "ELV/Data",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 1
  },
  {
    task_no: 119,
    wbs_code: "24.0",
    title: "24.0 RFQ Handover Activities",
    duration: "3 days",
    start: "2026-11-05",
    end: "2026-11-07",
    assignee: "PM,Client Engineer",
    trade: "Management",
    progress: 0,
    status: "Not Started",
    is_summary: 1,
    is_milestone: 0
  },
  {
    task_no: 120,
    wbs_code: "24.1",
    title: "Electrical testing and commissioning certificates signed",
    duration: "2 days",
    start: "2026-11-05",
    end: "2026-11-06",
    assignee: "PM,Client Engineer",
    trade: "Client/Consultant",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 121,
    wbs_code: "24.2",
    title: "CAT6 100% certification results complete with all failures corrected/retested",
    duration: "3 days",
    start: "2026-11-05",
    end: "2026-11-07",
    assignee: "PM,Client Engineer",
    trade: "Client/Consultant",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 122,
    wbs_code: "24.3",
    title: "TV/HDMI system commissioning complete",
    duration: "1 day",
    start: "2026-11-05",
    end: "2026-11-05",
    assignee: "PM,Client Engineer",
    trade: "ELV/Data",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },

  // Page 6
  {
    task_no: 123,
    wbs_code: "24.4",
    title: "Speaker/background-music commissioning complete",
    duration: "1 day",
    start: "2026-11-05",
    end: "2026-11-05",
    assignee: "PM,Client Engineer",
    trade: "ELV/Data",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 124,
    wbs_code: "24.5",
    title: "UPS testing, commissioning and network connection complete",
    duration: "1 day",
    start: "2026-11-05",
    end: "2026-11-05",
    assignee: "PM,Client Engineer",
    trade: "Electrical",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 125,
    wbs_code: "24.6",
    title: "Client personnel training completed for all systems",
    duration: "1 day",
    start: "2026-11-05",
    end: "2026-11-05",
    assignee: "PM,Client Engineer",
    trade: "Management",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 126,
    wbs_code: "24.7",
    title: "Electrical/data/AV as-fitted CAD and PDF issued with two hard-copy sets",
    duration: "3 days",
    start: "2026-11-05",
    end: "2026-11-07",
    assignee: "PM,Client Engineer",
    trade: "Engineering",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 127,
    wbs_code: "24.8",
    title: "O&M manuals, warranties and hard-copy operating manuals",
    duration: "2 days",
    start: "2026-11-05",
    end: "2026-11-06",
    assignee: "PM,Client Engineer",
    trade: "Engineering",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 128,
    wbs_code: "24.9",
    title: "Final snag list closed, legal waste receipt issued and final clean",
    duration: "2 days",
    start: "2026-11-05",
    end: "2026-11-06",
    assignee: "PM,Client Engineer",
    trade: "QA/QC",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 129,
    wbs_code: "25.0",
    title: "25.0 Week 6 - Commissioning",
    duration: "2 days",
    start: "2026-11-09",
    end: "2026-11-10",
    assignee: "Electrical Team",
    trade: "QA/QC",
    progress: 0,
    status: "Not Started",
    is_summary: 1,
    is_milestone: 0
  },
  {
    task_no: 130,
    wbs_code: "25.1",
    title: "Lighting, emergency, PIR, socket and desk-power functional tests",
    duration: "1 day",
    start: "2026-11-09",
    end: "2026-11-09",
    assignee: "Electrical Team",
    trade: "QA/QC",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 131,
    wbs_code: "25.2",
    title: "UPS, TV/HDMI and audio commissioning",
    duration: "1 day",
    start: "2026-11-10",
    end: "2026-11-10",
    assignee: "Electrical Team",
    trade: "QA/QC",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 0
  },
  {
    task_no: 132,
    wbs_code: "26.0",
    title: "26.0 Week 6 - Handover",
    duration: "1 day",
    start: "2026-11-11",
    end: "2026-11-11",
    assignee: "Electrical Team,PM",
    trade: "Management",
    progress: 0,
    status: "Not Started",
    is_summary: 1,
    is_milestone: 0
  },
  {
    task_no: 133,
    wbs_code: "26.1",
    title: "Snag close-out, as-fitted drawings, O&M, training and handover",
    duration: "1 day",
    start: "2026-11-11",
    end: "2026-11-11",
    assignee: "Electrical Team,PM",
    trade: "Management",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 1
  },
  {
    task_no: 134,
    wbs_code: "27.0",
    title: "27.0 Completion",
    duration: "1 day",
    start: "2026-11-11",
    end: "2026-11-11",
    assignee: "PM,Client Engineer",
    trade: "Management",
    progress: 0,
    status: "Not Started",
    is_summary: 1,
    is_milestone: 0
  },
  {
    task_no: 135,
    wbs_code: "27.1",
    title: "Project completion and acceptance",
    duration: "1 day",
    start: "2026-11-11",
    end: "2026-11-11",
    assignee: "PM,Client Engineer",
    trade: "Management",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 1
  },
  {
    task_no: 136,
    wbs_code: "28.0",
    title: "28.0 Programme Qualification",
    duration: "1 day",
    start: "2026-11-11",
    end: "2026-11-11",
    assignee: "PM,Client Engineer",
    trade: "Management",
    progress: 0,
    status: "Not Started",
    is_summary: 1,
    is_milestone: 0
  },
  {
    task_no: 137,
    wbs_code: "28.1",
    title: "Final programme note - subject to Client and Engineer approval following the joint site visit",
    duration: "1 day",
    start: "2026-11-11",
    end: "2026-11-11",
    assignee: "PM,Client Engineer",
    trade: "Management",
    progress: 0,
    status: "Not Started",
    is_summary: 0,
    is_milestone: 1
  }
];
